---
- hosts: all
  tasks:
  - include_role:
      name: zzet.rbenv
    vars:
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.5.5
        rubies:
          - version: 2.5.5
      rbenv_users:
        - vagrant

  - include_role:
      name: ocha.yarn
    vars:
      ansible_become: yes

  - include_role:
      name: geerlingguy.nodejs
    vars:
      ansible_become: yes

  - include_role:
      name: ANXS.postgresql
    vars:
      ansible_become: yes
      postgresql_ext_install_dev_headers: true
      postgresql_default_auth_method: "trust"
      postgresql_default_auth_method_hosts: "trust"

  - include_role:
      name: geerlingguy.redis
    vars:
      ansible_become: yes

  - include_role:
      name: gantsign.inotify
    vars:
      inotify_max_user_watches: 524288

  - include_role:
      name: tmux_conf
    vars:
      tmux_conf_users:
        - vagrant

  - include_role:
      name: unison
    vars:
      ansible_become: yes

  - include_role:
      name: tmuxp

  - name: Install htop
    apt: name=htop state=present
    become: yes

  - name: Install mc
    apt: name=mc state=present
    become: yes

  - name: Install ncdu
    apt: name=ncdu state=present
    become: yes

  - name: Create ~/projects directory
    file: path=~vagrant/projects state=directory
