---
- name: Install pip
  apt: name=python3-pip state=present
  become: yes

- name: Install venv
  apt: name=python3-venv state=present
  become: yes

- name: Install pipx
  shell: |
    python3 -m pip install --user pipx
    python3 -m pipx ensurepath

- name: Install tmuxp
  command: pipx install tmuxp
