---

- name: download unison
  get_url:
    url: https://github.com/TentativeConvert/Syndicator/raw/master/unison-binaries/unison-2.48.3
    dest: /usr/local/bin/unison
    mode: 755

- name: download unison-fsmonitor
  get_url:
    url: https://github.com/TentativeConvert/Syndicator/raw/master/unison-binaries/unison-fsmonitor
    dest: /usr/local/bin/unison-fsmonitor
    mode: 755
